version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./clickhouse/config/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql:ro
    environment:
      - CLICKHOUSE_DB=makro_pro
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
    entrypoint: /bin/bash -c "
      /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml &
      while ! nc -z localhost 9000; do   
        echo 'Waiting for ClickHouse to start...';   
        sleep 1; 
      done; 
      clickhouse-client -q 'CREATE DATABASE IF NOT EXISTS makro_pro;' --user admin --password admin"